### ISSUE TITLE
Why requiring nodejs 12? 

### ISSUE THREAD

**Issue by luizstacio** [dreamyguy/validate-color#2]
Some deploy automation platforms as in my case CodeBuild doesn't have support to node 12 by default. Then to install a check color that is mainly a nice string check thing. I need to completely change my build configs, I think is not a good restriction, maybe it is possible to remove it?!

**Comment by dreamyguy** [comment]
Sorry, just a bad habit of working on the latest LTS and keeping packages updated. I see it's not ideal in generic distributions.

Just pushed a new release without the restriction, that also solves a vulnerability warning that came up the other day. https://github.com/dreamyguy/validate-color/releases/tag/v1.0.4
