### ISSUE TITLE
"grey" colors

### ISSUE THREAD

**Issue by gepz** [dreamyguy/validate-color#26]
There are some "grey" (aliases for "gray") [color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color_keywords) not supported by this package, including:
DarkGrey
DarkSlateGrey
DimGrey
LightGrey
LightSlateGrey
Grey
SlateGrey

**Comment by dreamyguy** [comment]
Thanks for pointing this out @gepz, it came later than sooner, but it's here! ✨
