### ISSUE TITLE
NPM Package is empty

### ISSUE THREAD

**Issue by evanoc0** [dreamyguy/validate-color#7]
After running `npm i validate-color@1.0.7` for use in a node project, I was getting an error when trying to import the module like so
```js
import validateColor from "validate-color";
```

Checking the contents of `.../node_modules/validate-color/` I see it's missing any javascript files. It only has these contents:
<img width="695" alt="Screenshot 2020-04-09 at 13 12 48" src="https://user-images.githubusercontent.com/14321104/78893809-dd37e400-7a63-11ea-9e67-58f0b91e0872.png">

I'm getting the same when directly downloading the tarball listed on the npm registry.

**Comment by Cherry** [comment]
Experiencing this issue here too. Reverting to `1.0.6` includes the `lib` folder with the necessary files, but `1.0.7` only ships the files as shown in OP.

**Comment by dreamyguy** [comment]
My bad, I never ran the specific command that builds and moves files to their rightful folder, `lib/`. I've included it in the `deploy-npm` script, so I'll be less likely to forget running it first.

Here's the diff: https://github.com/dreamyguy/validate-color/compare/v1.0.7...v1.0.8

@evanoc0 and @Cherry many thanks for the heads-up, it's been an intense month...
